version: '3.1'

services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${SUPER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: juridicodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
      
