version: '3.1'

services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${SUPER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: juridico-container-postgres
    volumes:
      - /var/lib/docker/volumes/juridico-db/_data:/var/lib/postgresql/data  
      # - ./postgres:/var/lib/postgresql/data
      
